name: Sincronizar com Log de Atividade

# GATILHOS (Quando deve rodar)
on:
  # Quando um push for feito no branch 'main' ou 'master'
  push:
    branches: [main, master] # Ajuste se seu branch principal tiver outro nome
  
  # Quando um Pull Request for aberto ou fechado
  pull_request:
    types: [opened, closed] 

# TRABALHOS (O que deve fazer)
jobs:
  sync-to-notion:
    runs-on: ubuntu-latest # Usar uma máquina virtual padrão
    steps:

      # --- TRABALHO 1: Se o evento for um PUSH ---
      - name: Enviar Push para o Notion
        if: github.event_name == 'push'
        run: |
          # Pega a primeira linha da mensagem do commit
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          
          # Envia os dados para a API do Notion
          curl -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "${{ secrets.NOTION_DATABASE_ID }}" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "Push: ${{ env.COMMIT_MSG }}" } }] },
              "Status": { "status": { "name": "Push Direto" } },
              "Tipo": { "select": { "name": "Push" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pusher.name }}" } }] },
              "Data": { "date": { "start": "${{ github.event.head_commit.timestamp }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.ref_name }}" } }] },
              "Link": { "url": "${{ github.event.compare }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.ref_name }}" } }] }
            }
          }'

      # --- TRABALHO 2: Se o evento for um PULL REQUEST (ABERTO) ---
      - name: Enviar PR Aberto para o Notion
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          # Limpa a descrição do PR para evitar erros de JSON (remove aspas, etc.)
          PR_BODY=$(echo "${{ github.event.pull_request.body }}" | tr -d '"' | tr -d "'" | tr -d '\n' | tr -d '\r')

          curl -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "${{ secrets.NOTION_DATABASE_ID }}" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "PR: ${{ github.event.pull_request.title }}" } }] },
              "Status": { "status": { "name": "PR Aberto" } },
              "Tipo": { "select": { "name": "Pull Request" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.user.login }}" } }] },
              "Data": { "date": { "start": "${{ github.event.pull_request.created_at }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.head.ref }}" } }] },
              "Link": { "url": "${{ github.event.pull_request.html_url }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.base.ref }}" } }] },
              "Descrição": { "rich_text": [{ "text": { "content": "${{ env.PR_BODY }}" } }] }
            }
          }'

      # --- TRABALHO 3: Se o evento for um PULL REQUEST (MESCLADO) ---
      - name: Enviar PR Mesclado para o Notion
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          curl -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "${{ secrets.NOTION_DATABASE_ID }}" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "PR Mesclado: ${{ github.event.pull_request.title }}" } }] },
              "Status": { "status": {
