name: Sincronizar com Log de Atividade

# GATILHOS (Quando deve rodar)
on:
  # Quando um push for feito no branch 'main' ou 'master'
  push:
    branches: [main, master, develop]
  
  # Quando um Pull Request for aberto ou fechado
  pull_request:
    types: [opened, closed] 

# TRABALHOS (O que deve fazer)
jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:

      # --- TRABALHO 1: Se o evento for um PUSH ---
      - name: Enviar Push para o Notion
        if: github.event_name == 'push'
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          
          # A flag -f faz o script falhar (dar erro ❌) se o Notion retornar um erro
          curl -f -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${NOTION_API_KEY}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "'"${NOTION_DATABASE_ID}"'" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "Push: '"${COMMIT_MSG}"'" } }] },
              "Status": { "status": { "name": "Push Direto" } },
              "Tipo": { "select": { "name": "Push" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pusher.name }}" } }] },
              "Data": { "date": { "start": "${{ github.event.head_commit.timestamp }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.ref_name }}" } }] },
              "Link": { "url": "${{ github.event.compare }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.ref_name }}" } }] }
            }
          }'

      # --- TRABALHO 2: Se o evento for um PULL REQUEST (ABERTO) ---
      - name: Enviar PR Aberto para o Notion
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          PR_BODY=$(echo "${{ github.event.pull_request.body || 'Sem descrição.' }}" | tr -d '"' | tr -d "'" | tr -d '\n' | tr -d '\r' | head -c 1000)

          curl -f -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${NOTION_API_KEY}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "'"${NOTION_DATABASE_ID}"'" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "PR: ${{ github.event.pull_request.title }}" } }] },
              "Status": { "status": { "name": "PR Aberto" } },
              "Tipo": { "select": { "name": "Pull Request" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.user.login }}" } }] },
              "Data": { "date": { "start": "${{ github.event.pull_request.created_at }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.head.ref }}" } }] },
              "Link": { "url": "${{ github.event.pull_request.html_url }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.base.ref }}" } }] },
              "Descrição": { "rich_text": [{ "text": { "content": "'"${PR_BODY}"'" } }] }
            }
          }'

      # --- TRABALHO 3: Se o evento for um PULL REQUEST (MESCLADO) ---
      - name: Enviar PR Mesclado para o Notion
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          curl -f -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${NOTION_API_KEY}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "'"${NOTION_DATABASE_ID}"'" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "PR Mesclado: ${{ github.event.pull_request.title }}" } }] },
              "Status": { "status": { "name": "PR Mesclado" } },
              "Tipo": { "select": { "name": "Pull Request" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.user.login }}" } }] },
              "Data": { "date": { "start": "${{ github.event.pull_request.closed_at }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.head.ref }}" } }] },
              "Link": { "url": "${{ github.event.pull_request.html_url }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.base.ref }}" } }] }
            }
          }'

      # --- TRABALHO 4: Se o evento for um PULL REQUEST (FECHADO SEM MERGE) ---
      - name: Enviar PR Fechado para o Notion
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          curl -f -X POST https://api.notion.com/v1/pages \
          -H "Authorization: Bearer ${NOTION_API_KEY}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "'"${NOTION_DATABASE_ID}"'" },
            "properties": {
              "Atividade": { "title": [{ "text": { "content": "PR Fechado: ${{ github.event.pull_request.title }}" } }] },
              "Status": { "status": { "name": "PR Fechado" } },
              "Tipo": { "select": { "name": "Pull Request" } },
              "Autor": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.user.login }}" } }] },
              "Data": { "date": { "start": "${{ github.event.pull_request.closed_at }}" } },
              "Branch": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.head.ref }}" } }] },
              "Link": { "url": "${{ github.event.pull_request.html_url }}" },
              "Destino": { "rich_text": [{ "text": { "content": "${{ github.event.pull_request.base.ref }}" } }] }
            }
          }'
